### ISSUE TITLE
there is no 'setWorldPosition'

### ISSUE THREAD

**Issue by CodeIsJustLikeMagic** [thepowerprocess/UnitySpritePivotEditor#2]
I got an error when trying to compile the script because Unity doesn't know 'setWorldPosition'. Changing the line so it uses transform.position fixed the issue. I'm using Unity 2019.4
In any case the tool works very well and it saves me a lot of time and effort. Thanks for creating it!

**Comment by thepowerprocess** [comment]
Good catch.  Glad you're finding it useful.  Thanks for the feedback.
